@startuml

/'
class Main {
  run()
}
'/

/' クラスと関係の文字列を抽出。Plantuml::Classに渡してオブジェクトをもらう '/
/' relationはこの中でビルドしてPlantuml::Classに渡す'/
class Plantuml::Parser {
  classes
  relations
  ____
  {static} parse()

  .. private method ..
  _extract_class_strings()
  _extract_relation_strings()
}

/'クラス全体の文字列と、Relationオブジェクト全てをもらってクラスを組み立てる'/
class Plantuml::Class {
  name
  attribute
  variables
  methods
  relations
  {static} build()
}

class Plantuml::Class::Factory {
  {static} create()
  _check_is_method()
  _check_is_variable()
}

abstract class Plantuml::Class::Base {
  name
  attribute
  {static} build()
  is_method()
  is_variable()
}

class Plantuml::Class::Variable {
  name
  attribute
  {static} build()
  is_method()
  is_variable()
}

class Plantuml::Class::Method {
  name
  attribute
  {static} build()
  'check method'
  is_static()
  is_abstract()
  is_method()
  is_variable()
}

class Plantuml::Relation << (R,orchid) >> {
  from
  to
  name
  {static} build()
}

Plantuml::Class *-- Plantuml::Class::Variable
Plantuml::Class *-- Plantuml::Class::Method
Plantuml::Class <-- Plantuml::Relation
Plantuml::Class::Factory <-- Plantuml::Class
Plantuml::Class::Factory ..|> Plantuml::Class::Variable
Plantuml::Class::Factory ..|> Plantuml::Class::Method
Plantuml::Class::Variable -down-|> Plantuml::Class::Base
Plantuml::Class::Method -down-|> Plantuml::Class::Base

@enduml
